### ISSUE TITLE
List of functions to call.

### ISSUE THREAD

**Issue by topstrelok** [lsecqt/ThreadlessInject-C#1]
What other winapi calls can be used besides CreateEventW, and why is this particular api called?
UPD: I figured out the source code. The question is no longer relevant. Thank you

**Comment by lsecqt** [comment]
That is just for demonstrative purposes. CreateEventW is used when you try to save file with notepad.

Use apimonitor and analyze different programs to find suitable winapi to hook.

Usually suite winapi to hook means the one who is repeated on time intervals. Good luck!

**Comment by lsecqt** [comment]
Closing the issue
